version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install:install-file -Dfile=jltutils-2.1.jar -DgroupId=jltutils-2.1 -DartifactId=jltutils-2.1 -Dversion=2.1 -Dpackaging=jar -DlocalRepositoryPath=./lib
      - mvn package 

artifacts:
  files:
    - target/pok-datamining.war
  discard-paths: yes