version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean compile
      - mvn package
artifacts:
  files:
    - target/pok-datamining.war
  discard-paths: yes