version: 0.2

phases:
  pre_build:
    commands:
      - mvn install:install-file -Dfile=./lib/jltutils-2.1.jar -DgroupId=jltutils -DartifactId=jltutils -Dversion=2.1 -Dpackaging=jar -DlocalRepositoryPath=./lib-mvn
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package 

artifacts:
  files:
    - target/pok-datamining.war
  discard-paths: yes