version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install:install-file -Dfile=lib/jltutils-2.1.jar -DgroupId=jltutils \ -artifactId=jltutils -Dversion=2.1 -Dpackaging=jltutils
      - mvn package

artifacts:
  files:
    - target/pok-datamining.war
  discard-paths: yes