version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install:install-file -file=lib/jltutils-2.1.jar -groupId=jltutils \ -artifactId=jltutils -version=2.1 -packaging=jltutils
      - mvn package

artifacts:
  files:
    - target/pok-datamining.war
  discard-paths: yes